baseURL = "https://edalmava.github.io/hugo-tales/"
languageCode = "es-co"
title = "Mi nuevo Sitio en Hugo"
theme = "tale"
defaultContentLanguage = "es"
canonifyurls = true

[Author]
    name = "Edalmava"

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/post/"
	weight = 0